"""Update models with correct table names and relationships

Revision ID: 8a4b62644ac9
Revises: 2de0fa796365
Create Date: 2024-09-11 18:51:29.767213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4b62644ac9'
down_revision: Union[str, None] = '2de0fa796365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'price')
    # ### end Alembic commands ###
